// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjqoesfrehzcrtvrcktm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqcW9lc2ZyZWh6Y3J0dnJja3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4ODQyMDIsImV4cCI6MjA3MzQ2MDIwMn0.kAMe5Q9NhGHO1VJPOkg3X-Ab-hxHyOI8wo05PfOzngo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});